ketilmo/balena-ads-b

dump1090-fa/Dockerfile.template, piaware/Dockerfile.template
A quick way to get the latest version.  Maybe I can try and determine newer versions automatically when I have time.
=> Point to latest piaware version

README.md
Change logo to SVG to render better and add query params to auto-populate nicely
=> Change to SVG and add query params

balena.yml
Change-type: patch
Signed-off-by: Chris Crocker-White <chriscw@balena.io>
=> Update balena.yml to adhere to latest spec

README.md, balena.yml
Tested and in production Raspberry 40.
=> supported raspberrypi400-64

adsb-exchange/Dockerfile.template, adsb-exchange/convert.sh, adsb-exchange/create-sitename.sh, adsb-exchange/start.sh, dump1090-fa/start.sh
PLEASE TEST BEFORE MERGING :)
In regards to: https://github.com/ketilmo/balena-ads-b/issues/39
Thought i might just change what i have in mind, easier than ask you to do it all.
I'm not super familiar with how you build so i leave the testing up to you.
=> Updates to adsbexchange integration

.github/workflows/deploy-to-balena.yml, README.md
- Updates the checkout action to v4
- Fixes list numbering
- Fixes typos and mistakes
=> Update github action, fix typos and mistakes

.github/workflows/deploy-to-balena.yml
I think we should only try to run this from the master branch, until there is a better way to handle testing PRs.
=> Fix workflow for PRs

README.md, docker-compose.yml, wingbits/Dockerfile.template, wingbits/start.sh, wingbits/vector.yaml, wingbits/wingbits_installer.sh
@ketilmo I have added a definition here for wingbits service.
I'm also planning to do one for DeFli.
I just wanted to open this draft PR to start the discussion about contributing.
I will of course add documentation but just wanted to see if there was anything else you would want me to do to get this merged other than adding docs and squashing commits?
=> feat: add wingbits service

wingbits/Dockerfile.template, wingbits/start.sh
In latest version they've added the version number to /etc/wingbits/version and a version check script
=> add wingbits version number to usual location and version check on startup

README.md, dump1090-fa/Dockerfile.template
Remove blank line
Correct typo in readme
=> typo: remove unnecessary blank line and readme update

adsb-exchange/start.sh, docker-compose.yml, dump1090-fa/start.sh, dump978-fa/start.sh, fr24feed/start.sh, mlat-client/start.sh, opensky-network/start.sh, piaware/start.sh, planefinder/start.sh, radarbox/start.sh, traefik/start.sh, wingbits/start.sh
Stop disabled services, to free up memory.
=> Stop disabled services

README.md
fix dump978 instructions
Relates-to: #135
=> readme: fix dump978 instructions

README.md, adsb-exchange/start.sh, docker-compose.yml, dump1090-fa/start.sh, dump978-fa/start.sh, fr24feed/start.sh, kiosk/Dockerfile.template, kiosk/start.sh, mlat-client/start.sh, opensky-network/start.sh, piaware/start.sh, planefinder/start.sh, radarbox/start.sh, wifi-connect/Dockerfile.template, wifi-connect/start.sh, wingbits/start.sh
Modify service stop logic.
Fixes #133
Fixes #135
Closes #126
=> Modify service stop logic

docker-compose.yml, wifi-connect/Dockerfile.template, wifi-connect/package-lock.json, wifi-connect/package.json
Temporary fix for https://github.com/ketilmo/balena-ads-b/issues/142
- pull in required changes from https://github.com/balena-os/wifi-connect/pull/566
- increase timeout from 120 seconds to 180 seconds
- Fixes the error `D-Bus error: In D-Bus address, character '"' should have been escaped` due to incorrect env variable
Closes: https://github.com/ketilmo/balena-ads-b/issues/142
=> wifi-connect: temporary fix

wingbits/wingbits_installer.sh
Remove deprecated URL for vector installation
Closes: #152
=> wingbits: remove deprecated URL

adsb-exchange/Dockerfile.template, dump1090-fa/Dockerfile.template, dump978-fa/Dockerfile.template, fr24feed/Dockerfile.template, kiosk/Dockerfile.template, mlat-client/Dockerfile.template, piaware/Dockerfile.template, radarbox/Dockerfile.template, renovate.json, traefik/Dockerfile.template, wingbits/Dockerfile.template
=> Add renovate config

opensky-network/Dockerfile.template, renovate.json, wingbits/Dockerfile.template
Fix up renovate config for wingbits and opensky
You can see the working config here - https://github.com/shawaj/balena-ads-b/pulls
Relates-to: #155
=> renovate: fix up renovate config for wingbits and opensky

.github/workflows/deploy-to-balena-draft.yml
Draft deploy PRs to balena app so we can identify any build issues before merge
According to docs here... https://github.com/balena-io/deploy-to-balena-action?tab=readme-ov-file#usage
Closes: #170
=> feat: draft deploy PRs to balena app

wingbits/Dockerfile.template
=> chore: bump wingbits to bookworm

opensky-network/Dockerfile.template, wifi-connect/Dockerfile.template
bump wifi-connect and opensky to bookworm base
=> chore: bump wifi-connect and opensky to bookworm base

README.md, dump1090-fa/start.sh, dump978-fa/start.sh
- add device variable capability for setting dump978 gain
- fix idling for dump978 and dump1090 to enable setting serials
Closes: #177
=> feat: add dump978 gain variable

radarbox/Dockerfile.template
Fix up radarbox mlat install after #194
=> fix: radarbox mlat install

.github/workflows/deploy-to-balena-draft.yml
fix balena draft deploy when PR comes from forked repo
Closes: #173
=> fix: balena draft deploy on forked repos

.github/workflows/balena-preload.yml, .github/workflows/deploy-to-balena.yml
build balena preload image for each device supported
=> feat: get base image and preload apps

.github/workflows/balena-preload.yml
fix up balena preload for devices that do not match the device type of the fleet
=> fix: balena preload

renovate.json, wingbits/Dockerfile.template
=> fix: wingbits renovate

README.md, wingbits/Dockerfile.template
needed for GeoSigner dongle firmware updates
- add python3 and python3-pip and python3-venv
- add wget
- update readme to mention GeoSigner
=> wingbits: add python3 and wget and update readme

adsb-exchange/start.sh, autohupr/start.sh, dump1090-fa/start.sh, dump978-fa/start.sh, fr24feed/start.sh, kiosk/start.sh, mlat-client/start.sh, opensky-network/start.sh, piaware/start.sh, planefinder/start.sh, planewatch/start.sh, radarbox/start.sh, traefik/start.sh, wifi-connect/start.sh, wingbits/start.sh
=> Add curl retry for supervisor

wingbits/start.sh
- add mechanism for idling container to allow for manually flashing geosigner
- add mechanism for override of release hash to check for errors in new releases or force a dev release for example
- print architecture
- change version check to suit new client
Relates-to: #230
=> wingbits: add idling mechanism and release hash override

README.md
add link to SDR enthusiasts discord server and balena-ads-b channel
=> readme: add link to SDR enthusiasts discord

README.md
Add note about geosigner commands
Closes: #258
=> wingbits: add note about geosigner commands

README.md
=> fix: another link typo

opensky-network/opensky_installer.sh
=> Fix OpenSky Network installation

renovate.json
Quick update to renovate config to fix URL change to OpenSky Network repo.
=> Updated renovate config for OpenSky Network.

wingbits/start.sh
adds dump978 / UAT ingestion capability to wingbits container
=> wingbits: add dump978 / UAT ingestion

adsb-exchange/start.sh, airnav-radar/start.sh, autohupr/start.sh, dump1090-fa/start.sh, dump978-fa/start.sh, fr24feed/start.sh, kiosk/start.sh, mlat-client/start.sh, opensky-network/start.sh, piaware/start.sh, planefinder/start.sh, planewatch/start.sh, tar1090/00-startup-checks, traefik/start.sh, wifi-connect/start.sh, wingbits/start.sh
=> Fix curl command
